;==========================================================
;   POLYBAR - TEAL & FUCHSIA FLOATING THEME
;==========================================================

[colors]
background = #0F111A
background-alt = #1A1D2D
foreground = #FFFFFF
foreground-alt = #94A3B8

; Palet Teal & Fuchsia
teal = #008080
fuchsia = #D946EF
purple = #A855F7
disabled = #475569

[bar/main]
bottom = true

; Ukuran dan jarak mengambang (Floating margin)
width = 98%
height = 28pt
offset-x = 1%
offset-y = 5px
radius = 10

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2pt

border-size = 0pt
border-color = #1E2235

; Ujung kiri & kanan bar rapat ke tombol
padding-left = 0
padding-right = 0

; DIBUAT 0 AGAR JARAK ANTAR MODUL RAPAT (HANYA MENGANDALKAN SEPARATOR 1 SPASI)
module-margin = 0

separator = " "

font-0 = "JetBrains Mono:pixelsize=9;3"
font-1 = "Font Awesome 6 Free Solid:pixelsize=9;3"

; Tambahkan font khusus icon besar di sini:
font-2 = "Font Awesome 6 Free Solid:pixelsize=14;3"

modules-left = launcher bspwm xwindow
modules-right = cpu memory pulseaudio mic batteryscript systray network mprisence date powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
wm-restack = bspwm

; ==========================================================
; TOMBOL KIRI (MEPET KE UJUNG KIRI & RAPAT KE BSPWM)
; ==========================================================
[module/launcher]
type = custom/text
format = ""
format-font = 3
format-background = ${colors.teal}
format-foreground = ${colors.foreground}
format-padding = 2
click-left = rofi -show drun -show-icons

; ==========================================================
; WORKSPACE BSPWM
; ==========================================================
[module/bspwm]
type = internal/bspwm

# Workspace yang sedang diakses (Aktif / Focused)
label-focused = 
label-focused-background = ${colors.background-alt}
label-focused-foreground = ${colors.teal}
label-focused-underline = ${colors.teal}
label-focused-padding = 1

# Workspace yang tidak diakses tapi ada isinya (Occupied)
label-occupied = ●
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1

# Workspace yang kosong (Empty)
#label-empty = ◆
label-empty = •
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

; ==========================================================
; JUDUL APLIKASI
; ==========================================================
[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%
label-foreground = ${colors.foreground-alt}
label-padding = 1

; ==========================================================
; MONITOR SYSTEM (CPU & RAM)
; ==========================================================
[module/cpu]
type = internal/cpu
interval = 2

format-foreground = ${colors.fuchsia}
format = %{A1:~/.config/bspwm/scripts/htop.sh:} <label>%{A}
label = %percentage:2%%
label-foreground = ${colors.foreground}


[module/memory]
type = internal/memory
interval = 2

format-foreground = ${colors.teal}
format = %{A1:~/.config/bspwm/scripts/htop.sh:} <label>%{A}
label = %percentage_used:2%%
label-foreground = ${colors.foreground}

; ==========================================================
; AUDIO: SPEAKER (HANYA IKON SAAT MUTE)
; ==========================================================
[module/pulseaudio]
type = internal/pulseaudio

use-ui-max = false

;format-volume = %{A1:~/.config/bspwm/scripts/pavucontrol.sh speaker:}<ramp-volume> <label-volume>%{A}
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.teal}

format-muted = <label-muted>
label-muted = ""
label-muted-foreground = ${colors.fuchsia}

;click-left = pavucontrol
click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
click-right = ~/.config/bspwm/scripts/pavucontrol.sh speaker

; ==========================================================
; AUDIO: MICROPHONE
; ==========================================================
[module/mic]
type = custom/script

exec = sh -c 'if pactl get-source-mute @DEFAULT_SOURCE@ | grep -q "yes"; then echo "%{F#D946EF}%{F-}"; else vol=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -o "[0-9]*%" | head -n 1); echo "%{F#D946EF}%{F-} $vol"; fi'
interval = 1

format = <label>
label = %output%
label-foreground = ${colors.foreground}

scroll-up = sh -c 'pactl set-source-volume @DEFAULT_SOURCE@ +5%; v=$(pactl get-source-volume @DEFAULT_SOURCE@ | grep -o "[0-9]*%" | head -n 1 | tr -d "%"); [ "$v" -gt 100 ] && pactl set-source-volume @DEFAULT_SOURCE@ 100%'
scroll-down = pactl set-source-volume @DEFAULT_SOURCE@ -5%

click-left = pactl set-source-mute @DEFAULT_SOURCE@ toggle
click-right = ~/.config/bspwm/scripts/pavucontrol.sh mic

; ==========================================================
; NETWORK STATS
; ==========================================================
[module/network]
type = internal/network
interface = wlan0
interval = 1.0

label-connected = "%{F#008080}%downspeed:7% %{F#D946EF}%upspeed:7%"
label-connected-foreground = ${colors.foreground}
format-disconnected =

; ==========================================================
; JAM & TANGGAL
; ==========================================================
[module/date]
type = internal/date
interval = 1

; Tampilan biasa (hanya jam)
date = %H:%M

; Tampilan saat diklik kiri (alt)
date-alt = %a, %d %b %Y - %H:%M

; Gunakan tag %{A3:...} untuk klik kanan
label = "%{A3:~/.config/bspwm/scripts/gsimplecal.sh:}%date% %{A}"
label-foreground = ${colors.foreground}

; ==========================================================
; BATTERAY & AC
; ==========================================================
[module/batteryscript]
type = custom/script
exec = ~/.config/bspwm/scripts/battery.sh
interval = 3

[module/battery]
type = internal/battery
poll-interval = 2

# Cek nama baterai & adapter Anda dengan perintah: ls -1 /sys/class/power_supply/
battery = BAT0
adapter = AC

# Ambang batas dianggap penuh / full AC power
full-at = 98
low-at = 20

format-full-prefix = " "
format-full-prefix-foreground = ${colors.teal}
format-full = <label-full>
label-full = %percentage%%
label-full-foreground = ${colors.foreground}

# CHARGING
format-charging-prefix = " "
format-charging-prefix-foreground = ${colors.teal}
format-charging = <label-charging>
label-charging = %percentage%%
label-charging-foreground = ${colors.foreground}

# DISCHARGING
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-foreground = ${colors.foreground}

# Icon baterai bertingkat (Otomatis berubah sesuai level daya)
ramp-capacity-0 = " "
ramp-capacity-1 = " "
ramp-capacity-2 = " "
ramp-capacity-3 = " "
ramp-capacity-4 = " "
ramp-capacity-foreground = ${colors.fuchsia}

# BATERAI (LOW)
format-low = <ramp-capacity> <label-low>
label-low = %percentage%%!
label-low-foreground = ${colors.foreground}

; ==========================================================
; SYSTEM TRAY
; ==========================================================
[module/systray]
type = internal/tray
format-margin = 0pt
tray-spacing = 2pt
tray-size = 55%

; ==========================================================
; TOMBOL KANAN (MEPET KE UJUNG KANAN & RAPAT KE DATE)
; ==========================================================
[module/powermenu]
type = custom/text
format = ""
format-font = 3
format-background = ${colors.fuchsia}
format-foreground = ${colors.foreground}
format-padding = 2
click-left = ~/.config/rofi/powermenu.sh

; ==========================================================
; MPRISENCE
; ==========================================================
[module/mprisence]
type = custom/script
exec = ~/.config/mprisence/mprisence.sh
interval = 2
click-left = ~/.config/mprisence/mprisence.sh --toggle
click-right = notify-send -r 9991 -t 2000 -u low -i multimedia-audio-player "MPRISence" "Click to open Aimp"
cursor-click = pointer

[settings]
screenchange-reload = true
pseudo-transparency = true
